jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: AzurePowerShell@5
    displayName: Azure PowerShell script to get storage account keys
    inputs:
      ConnectedServiceNameARM: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
      ScriptType: InlineScript
      Inline: "# You can write your azure powershell scripts inline here. \n# You can also pass predefined and custom variables to this script using arguments\n\n$key=(Get-Azstorageaccountkey -ResourceGroupName BHGroup -AccountName adestoress).value[0]\n\nWrite-host \"##vso[task.setvariable variable=storagekey]$key\" "
      CustomTargetAzurePs: 2.6.0
  - task: replacetokens@5
    displayName: Replace tokens in Terraform script
    inputs:
      targetFiles: '**/*.tf'
  - task: TerraformInstaller@1
    displayName: Install Terraform latest
  - task: TerraformTaskV4@4
    displayName: 'Terraform : init'
    inputs:
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC
      backendServiceArm: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
      backendAzureRmResourceGroupName: BHGroup
      backendAzureRmStorageAccountName: adestoress
      backendAzureRmContainerName: newcontainer
      backendAzureRmKey: terraform.tfstate
  - task: TerraformTaskV4@4
    displayName: 'Terraform : Plan'
    inputs:
      command: plan
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC
      environmentServiceNameAzureRM: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
  - task: TerraformTaskV4@4
    displayName: 'Terraform : Apply'
    inputs:
      command: apply
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC
      environmentServiceNameAzureRM: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
...
