jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: TerraformInstaller@1
    displayName: Install Terraform latest
  - task: TerraformTaskV4@4
    displayName: 'Terraform : init'
    inputs:
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC for ACR
      backendServiceArm: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
      backendAzureRmResourceGroupName: BHGroup
      backendAzureRmStorageAccountName: adeolastores
      backendAzureRmContainerName: https://adeolastores.blob.core.windows.net/newcontainer?sp=r&st=2023-03-07T13:40:32Z&se=2023-03-07T21:40:32Z&spr=https&sv=2021-06-08&sr=c&sig=ARovW9PwPOEa0ZP12n133RUijbQFfSVwlc1PPd%2FSEOo%3D
      backendAzureRmKey: terraform.tfstate
  - task: TerraformTaskV4@4
    displayName: 'Terraform : plan'
    inputs:
      command: plan
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC for ACR
      environmentServiceNameAzureRM: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
  - task: TerraformTaskV4@4
    displayName: 'Terraform : Apply'
    inputs:
      command: apply
      workingDirectory: $(System.DefaultWorkingDirectory)/IAC for ACR
      environmentServiceNameAzureRM: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
...
