name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@0
    displayName: Build an image
    inputs:
      azureSubscriptionEndpoint: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
      azureContainerRegistry: '{"loginServer":"adeolabhregistry.azurecr.io", "id" : "/subscriptions/8ba999a2-749c-4dd2-9e8f-d0e1a0bc1858/resourceGroups/AdeolaBHresource-group/providers/Microsoft.ContainerRegistry/registries/AdeolaBHregistry"}'
      dockerFile: dockerfile
      imageName: AdeImage-$(Build.Repository.Name):$(Build.BuildId)
  - task: Docker@0
    displayName: Push an image
    inputs:
      azureSubscriptionEndpoint: f7460b28-ef4e-4d55-89f6-0ab2060f6c5d
      azureContainerRegistry: '{"loginServer":"adeolabhregistry.azurecr.io", "id" : "/subscriptions/8ba999a2-749c-4dd2-9e8f-d0e1a0bc1858/resourceGroups/AdeolaBHresource-group/providers/Microsoft.ContainerRegistry/registries/AdeolaBHregistry"}'
      action: Push an image
      imageName: AdeImage-$(Build.Repository.Name):$(Build.BuildId)
...
